export interface MessageUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  reasoningTokens?: number; // Tokens de raciocínio (thinking)
  cachedTokens?: number; // Tokens lidos do cache
  cost: number; // Custo em créditos/dólares
  upstreamCost?: number; // Custo upstream (BYOK)
  apiKeyName?: string; // Nome da API Key usada
  reasoningEnabled?: boolean; // Se reasoning estava ativo
  reasoningEffort?: 'low' | 'medium' | 'high'; // Intensidade do reasoning (OpenAI)
  reasoningMaxTokens?: number; // Max tokens do reasoning (Anthropic, Gemini, Qwen)
}

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  createdAt: Date;
  model?: string;
  webSearchEnabled?: boolean;
  citations?: Citation[];
  attachments?: Attachment[];
  generatedImages?: GeneratedImage[]; // Images generated by AI
  isFavorite?: boolean;
  isStreaming?: boolean;
  reasoning?: string; // Reasoning tokens (thinking process)
  reasoningDetails?: ReasoningDetail[]; // Full reasoning details from OpenRouter
  usage?: MessageUsage; // Dados de uso do request
  // Debate-specific fields (optional for regular messages)
  participantName?: string; // Name of the debate participant
  debateRole?: 'participant1' | 'participant2' | 'moderator'; // Role in debate
}

export interface Citation {
  title: string;
  url: string;
  snippet?: string;
  content?: string; // Added by OpenRouter if available
  start_index?: number; // Index in message content
  end_index?: number; // Index in message content
}

export interface Attachment {
  id: string;
  name: string;
  type: string; // MIME type (image/*, application/pdf, audio/*, application/vnd.openxmlformats-officedocument.wordprocessingml.document, text/plain)
  size: number;
  url: string; // Firebase Storage URL
  preview?: string;
  storageRef?: string; // Firebase Storage reference path
  base64?: string; // For audio files (required by OpenRouter)
  isActive?: boolean; // Whether attachment is active in conversation context (default: true)
}

export interface GeneratedImage {
  id: string;
  url: string; // Firebase Storage URL
  storageRef: string; // Firebase Storage reference path
  createdAt: Date;
  size?: number; // File size in bytes
}

export interface Chat {
  id: string;
  name: string;
  lastMessageAt: Date;
  createdAt: Date;
  folderId?: string;
  isArchived?: boolean;
  isFavorite?: boolean;
  isProtected?: boolean;
  isPinned?: boolean;
  messages?: Message[];
  systemPrompt?: string;
  context?: string;
  password?: string;
  latexEnabled?: boolean;
  latexLevel?: 'medio' | 'superior';
  temperature?: number;
  frequencyPenalty?: number;
  repetitionPenalty?: number;
  maxTokens?: number;
  lastMessage?: string;
  messageCount?: number;
  order?: number;
  selectedModel?: string; // Último modelo usado neste chat
  memories?: Memory[]; // Memórias específicas deste chat
  guidedStudyEnabled?: boolean; // Modo de estudo guiado ativo neste chat
  webSearchEnabled?: boolean; // Web Search ativo neste chat
  deepThinkingEnabled?: boolean; // Deep Thinking ativo neste chat
  deepThinkingDepth?: 'Baixa' | 'Média' | 'Alta'; // Profundidade do Deep Thinking (para modelos com effort)
  reasoningMaxTokens?: number; // Max tokens para reasoning (para modelos do Google, Anthropic, Qwen)
  totalCost?: number; // Custo total acumulado em dólares (OpenRouter)
  totalTokens?: number; // Total de tokens usados em todas as mensagens
  // Estatísticas do chat
  stats?: ChatStats;
  // Debate mode
  isDebate?: boolean; // Se este chat é um debate
  debateConfig?: DebateConfig; // Configuração do debate (se aplicável)
  // Persona mode
  isPersona?: boolean; // Se este chat é um chat de Persona
  personaConfig?: PersonaConfig; // Configuração da Persona (se aplicável)
  // Automatic naming system
  isTemporary?: boolean; // Se o nome do chat é temporário e será substituído
  createdManually?: boolean; // Se o chat foi criado via modal ou automaticamente
  isFirstMessage?: boolean; // Se a próxima mensagem é a primeira (para system prompt de nomeação)
}

export interface ChatStats {
  totalCharacters: number; // Total de caracteres
  userCharacters: number; // Caracteres do usuário
  aiCharacters: number; // Caracteres da IA
  avgSentencesPerMessage: number; // Média de frases por mensagem
  estimatedReadingTimeMinutes: number; // Tempo estimado de leitura em minutos
  wordFrequency: Record<string, number>; // Frequência de palavras
  lastUpdated: Date; // Última vez que as estatísticas foram calculadas
}

export interface Folder {
  id: string;
  name: string;
  color?: string;
  password?: string;
  isExpanded: boolean;
  chats: Chat[];
  createdAt: Date;
  parentFolderId?: string | null; // For subfolder hierarchy
  subfolders?: Folder[]; // Nested subfolders
}

export interface ChatConfig {
  name: string;
  systemPrompt: string;
  context: string;
  password: string;
  latexEnabled: boolean;
  latexLevel: 'medio' | 'superior';
  temperature: number;
  frequencyPenalty: number;
  repetitionPenalty: number;
  maxTokens: number;
  memories?: Memory[];
  isDebate?: boolean;
  debateConfig?: DebateConfig;
}

export type PDFEngine = 'mistral-ocr' | 'pdf-text' | 'native';

export interface UserSettings {
  pdfEngine: PDFEngine;
}

// Reasoning types based on OpenRouter documentation
export interface ReasoningDetail {
  type: 'reasoning.summary' | 'reasoning.encrypted' | 'reasoning.text';
  id: string | null;
  format: 'unknown' | 'openai-responses-v1' | 'anthropic-claude-v1';
  index?: number;
  summary?: string; // For reasoning.summary
  data?: string; // For reasoning.encrypted
  text?: string; // For reasoning.text
  signature?: string | null; // For reasoning.text
}

export interface ReasoningConfig {
  enabled: boolean;
  effort?: 'low' | 'medium' | 'high'; // For OpenAI models (o1, o3, GPT-5, Grok)
  max_tokens?: number; // For Gemini, Anthropic, Qwen models
  exclude?: boolean; // Set to true to exclude reasoning tokens from response (model still uses reasoning internally)
}

export interface WebSearchConfig {
  enabled: boolean;
  engine?: 'native' | 'exa' | undefined; // undefined = auto (native if available, else exa)
  max_results?: number; // Default 5
  search_prompt?: string; // Custom search prompt
}

// Memory types
export interface Memory {
  id: string;
  content: string;
  color: string;
  createdAt: Date;
}

// API Key types
export type TranscriptionProvider = 'gemini';

export interface OpenRouterApiKey {
  id: string; // Unique identifier for this API key
  name: string; // User-friendly name for the key (e.g., "Personal", "Work")
  encryptedKey: string; // Encrypted API key using AES-256-GCM
  provider: TranscriptionProvider; // Provider: 'openrouter' or 'gemini'
  isActive: boolean; // Whether this key is currently active
  createdAt: Date;
  lastUsedAt?: Date; // Track when this key was last used
}

// AI Personality types
export interface AIPersonality {
  id: string; // Unique identifier
  name: string; // Name of the personality (e.g., "Professional", "Friendly")
  description: string; // User-defined personality instructions
  isActive: boolean; // Whether this personality is currently active
  createdAt: Date;
  updatedAt: Date;
}

// Persona types (complete identity replacement, not personality add-on)
export interface Persona {
  id: string;
  name: string; // Nome da Persona (ex: "Dr. Silva", "Coach Max")
  personality: string; // Traços de personalidade e comportamento
  description: string; // Contexto, expertise e background
  dialogExamples?: string; // Exemplos de diálogos para demonstrar estilo (opcional)
  firstMessage?: string; // Primeira mensagem que a Persona envia ao iniciar chat (opcional)
  alwaysDo?: string; // Diretrizes de comportamentos que a persona deve sempre seguir (opcional)
  neverDo?: string; // Diretrizes de comportamentos que a persona nunca deve fazer (opcional)
  maxTokens?: number; // Limite máximo de tokens nas respostas (opcional)
  isPinned?: boolean; // Se a Persona está fixada no topo
  createdAt: Date;
  updatedAt: Date;
}

// PersonaConfig é um snapshot imutável embedado no Chat
// (preserva contexto histórico mesmo se a Persona original for editada/deletada)
export interface PersonaConfig {
  personaId: string; // Referência à Persona original (para rastreamento)
  name: string;
  personality: string;
  description: string;
  dialogExamples?: string;
  firstMessage?: string;
  alwaysDo?: string;
  neverDo?: string;
  maxTokens?: number; // Limite máximo de tokens nas respostas (opcional)
}

// Debate Mode types
export type DebatePosition = 'a_favor' | 'contra' | 'neutro';

export interface DebateParticipant {
  name: string;
  model: string; // OpenRouter model identifier
  position: DebatePosition;
  maxTokens?: number; // Max tokens for this participant's model
}

export interface DebateConfig {
  participant1: DebateParticipant;
  participant2: DebateParticipant;
  topic: string;
  points: string[]; // Array of debate points/agendas
  moderatorName: string;
  editable?: boolean; // If true, debate can be edited (paused state)
}

export interface DebateMessage extends Message {
  participantName?: string; // Name of the debate participant
  isModeratorMessage?: boolean; // Whether this is a moderator intervention
  debateRole?: 'participant1' | 'participant2' | 'moderator';
}

export interface DebateSession {
  id: string;
  config: DebateConfig;
  messages: DebateMessage[];
  currentTurn: 'participant1' | 'participant2' | null;
  isActive: boolean;
  isPaused: boolean;
  hasStarted: boolean;
  createdAt: Date;
  systemPromptTemplate: string; // The debate system prompt template
}

// Chat Sharing types
export type ShareType = 'copy' | 'collaborative';

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  photoURL?: string;
  photoStoragePath?: string;
  chatBackgroundURL?: string;
  chatBackgroundPath?: string;
  openRouterApiKey?: string; // Deprecated - kept for backward compatibility
  openRouterApiKeys?: OpenRouterApiKey[]; // Array of multiple API keys
  pdfEngine?: PDFEngine;
  defaultModel?: string; // Modelo padrão para novos chats
  transcriptionModel?: string; // Modelo Gemini usado para transcrição de áudio
  fontFamily?: string; // Fonte do chat
  fontSize?: number; // Tamanho da fonte do chat
  theme?: 'light' | 'dark' | 'dracula'; // Tema da interface
  favoriteModels?: string[]; // Modelos favoritados pelo usuário
  modelUsageCount?: Record<string, number>; // Contagem de uso de cada modelo
}

export interface SharedChat {
  id: string; // Unique share ID
  chatId: string; // Original chat ID
  ownerId: string; // Owner user ID
  ownerEmail: string; // Owner email for display
  shareType: ShareType;
  members: string[]; // Array of user IDs with access
  inviteCode?: string; // Current active invite code
  createdAt: Date;
  expiresAt?: Date; // Optional expiration
  isActive: boolean;
  chatMetadata: {
    name: string;
    messageCount: number;
    lastMessageAt: Date;
  };
}

export interface ShareInvite {
  id: string; // Unique invite ID
  shareId: string; // Reference to SharedChat
  code: string; // Unique invite code
  shareType: ShareType;
  chatId: string; // Original chat ID
  ownerId: string; // Owner user ID
  ownerEmail: string; // Owner email
  chatName: string; // Chat name for preview
  createdBy: string; // User ID who created the invite
  createdAt: Date;
  expiresAt?: Date; // Optional expiration
  usedBy?: string; // User ID who accepted
  usedAt?: Date; // When it was accepted
  isActive: boolean; // Can still be used
}

export interface FailedTranscription {
  id: string;
  userId: string;
  storagePath: string;
  audioFileName: string;
  audioDurationSeconds?: number;
  errorMessage: string;
  errorType: 'api_error' | 'timeout' | 'rate_limit' | 'invalid_format' | 'network_error' | 'unknown';
  recordedAt: Date;
  failedAt: Date;
  retryCount: number;
  lastRetryAt?: Date;
  fileSize: number;
}


